.PHONY: clean All

All:
	@echo "----------Building project:[ MoveSemantics - Debug ]----------"
	@cd "MoveSemantics" && "$(MAKE)" -f  "MoveSemantics.mk"
clean:
	@echo "----------Cleaning project:[ MoveSemantics - Debug ]----------"
	@cd "MoveSemantics" && "$(MAKE)" -f  "MoveSemantics.mk" clean
